# OSM-RCAF Hungarian translation
# Copyright (C) 2023 Attila Kun
# This file is distributed under the same license as the OSM-RCAF package.
# Attila Kun <attila [at] attilakundev [dot] com>, 2023.
#
#, fuzzy
msgid   ""
msgstr  "Project-Id-Version: PACKAGE VERSION\n"
        "Report-Msgid-Bugs-To: \n"
        "POT-Creation-Date: 2023-01-12 07:22+0100\n"
        "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
        "Last-Translator: Attila Kun <attila [at] attilakundev [dot] com>\n"
        "Language-Team: N/A\n"
        "Language: Hungarian\n"
        "MIME-Version: 1.0\n"
        "Content-Type: text/plain; charset=UTF-8\n"
        "Content-Transfer-Encoding: 8bit\n"

#: lib/osm_error_messages.py:32
#, python-brace-format
msgid   "Previous way's first and last nodes: {first_node_previous} and "
        "{last_node_previous}\n"
        "Role: {previous_role}\n"
        "Roundabout: {previous_roundabout}\n"
        "One way road: {previous_oneway}\n"
        "Current way's first and last nodes: {first_node_current} and "
        "{last_node_current}\n"
        "Role: {current_role}\n"
        "Roundabout: {current_roundabout}\n"
        "One way road: {current_oneway}\n"
msgstr  ""

#: lib/osm_error_messages.py:55
#, python-brace-format
msgid   "Previous way's first and last nodes: {first_node_previous} and "
        "{last_node_previous}\n"
        "Role: {previous_role}\n"
        "Current way's first and last nodes: {first_node_current} and "
        "{last_node_current}\n"
        "Role: {current_role}\n"
msgstr  ""

#: lib/osm_error_messages.py:79
#, python-brace-format
msgid   "=================[Relation #{relation_id}]================="
msgstr  ""

#: lib/osm_error_messages.py:81
#, python-brace-format
msgid   "Link of the relation: {relation}"
msgstr  ""

#: lib/osm_error_messages.py:84
#, python-format, python-brace-format
msgid   "This relation has {errors} errors and {correct_ways_count} correct "
        "ways. That's {correctness}% correct."
msgstr  ""

#: lib/osm_error_messages.py:102
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has gap "
        "at way: {current_ref}\n"
        "This case occured because there is a gap,this happened at the "
        "beginning of the relation, since it started with a 2x2 seperated "
        "highway. The ID of last way before going to backward direction: "
        "{last_forward_way_before_backward_direction}\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:117
#, python-brace-format
msgid   "\n"
        "INFO: There is a roundabout split up to multiple ways, last known "
        "way is {current_ref}\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:124
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has a "
        "road segment which has forward role, but not oneway and the "
        "following road segment is a normal road segment, way number where "
        "this was found: {current_ref}\n"
        " Previous way:{previous_ref}\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:136
#, python-brace-format
msgid   "ERROR Relation with route number {currently_checked_ref} has wrong "
        "role setup at way:"
msgstr  "HIBA Relation with route number {currently_checked_ref} has wrong "
        "role setup at way:"

#: lib/osm_error_messages.py:141
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has gap "
        "at roundabout: {current_ref}\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:149
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has gap "
        "at way: {current_ref}\n"
        " It's found in a series of ways with forward role.\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:159
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has gap "
        "at way: {current_ref}\n"
        " There is only one connecting way into the closed (its start and end "
        "nodes are the same) roundabout instead of two.\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:170
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has the "
        "way {current_ref} earlier than needed, it's a roundabout entry node "
        "and it should be swapped in order to maintain the continuity. \n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:181
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has the "
        "way {current_ref} roundabout way duplicated, this is wrong, since "
        "the route only contains the roundabout once. \n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:192
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has a "
        "roundabout {current_ref}  with forward role missing. \n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:202
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has a one-"
        "way road {previous_ref}  with forward role missing. \n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:212
msgid   "\n"
        "[WARNING] The motorway is continuous, however it reached back from "
        "start point to (almost) start point via other lane. It should be "
        "done that the motorway's right lane goes first to the end point, "
        "then left lane from first to end point."
msgstr  ""

#: lib/osm_error_messages.py:218
#, python-brace-format
msgid   "\n"
        "[ERROR] Relation with route number {currently_checked_ref} has gap "
        "at way: {current_ref}\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:233
#, python-brace-format
msgid   "\n"
        "[ERROR] Multipolygon has an area consisting of one way unclosed, the "
        "way affected: {current_ref}\n"
        "\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:240
#, python-brace-format
msgid   "\n"
        "[ERROR] Multipolygon has an area consisting of one way unclosed at "
        "the end of the relation, the way affected: {current_ref}\n"
        "\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:247
#, python-brace-format
msgid   "\n"
        "[ERROR] Multipolygon has an area consisting of multiple ways "
        "unclosed at the end of the relation, the way affected: "
        "{current_ref}\n"
        "\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:254
#, python-brace-format
msgid   "\n"
        "[ERROR] Multipolygon has an area consisting of multiple ways "
        "unclosed, the way affected: {current_ref}\n"
        "\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:261
#, python-brace-format
msgid   "\n"
        "[ERROR] Multipolygon has a way which doesn't have a role, the way "
        "affected: {current_ref}\n"
        "\n"
        "{nodes}"
msgstr  ""

#: lib/osm_error_messages.py:269
msgid   "This relation has no errors and gaps at all."
msgstr  ""
